language: ruby
sudo: false
before_install:
  - gem install bundler
dist: trusty
rvm:
  - 2.4
script: bundle exec rake test
notifications:
  email: false
env:
  global:
    - GH_CLIENT_ID='client_id-foo'
    - GH_CLIENT_SECRET='client_secret-bar'
